/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-09 06:26:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class member_005fjoin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>쇼핑몰</title>\r\n");
      out.write("<script>\r\n");
      out.write("function check(){\r\n");
      out.write("	var id=joinform.MEMBER_ID.value;\r\n");
      out.write("	var password1=joinform.MEMBER_PW.value;\r\n");
      out.write("	var password2=joinform.MEMBER_PW2.value;	\r\n");
      out.write("	var email1=joinform.MEMBER_EMAIL1.value;\r\n");
      out.write("	var email2=joinform.MEMBER_EMAIL2.value;\r\n");
      out.write("	var phone=joinform.MEMBER_PHONE.value;\r\n");
      out.write("	var addr1=joinform.MEMBER_ADDR1.value;\r\n");
      out.write("	var addr2=joinform.MEMBER_ADDR2.value;\r\n");
      out.write("	var mobile=joinform.MEMBER_MOBILE.value;\r\n");
      out.write("	\r\n");
      out.write("	var forms = document.getElementById(\"joinform\");\r\n");
      out.write("\r\n");
      out.write("	if ((forms.MEMBER_NAME.value==\"\")||(forms.MEMBER_NAME.value.length<=1)){\r\n");
      out.write("		alert(\"이름을 제대로 입력해 주세요.\");\r\n");
      out.write("		forms.MEMBER_NAME.focus();\r\n");
      out.write("         		return false;\r\n");
      out.write("	}\r\n");
      out.write("	if(id.length == 0){\r\n");
      out.write("		alert(\"아이디를 입력하세요.\");\r\n");
      out.write("		joinform.MEMBER_ID.focus();\r\n");
      out.write("		return false;\r\n");
      out.write("	}\r\n");
      out.write("	if(password1.length == 0){\r\n");
      out.write("		alert(\"비밀번호를 입력하세요.\");\r\n");
      out.write("		joinform.MEMBER_PW.focus();\r\n");
      out.write("		return false;\r\n");
      out.write("	} \r\n");
      out.write("	if(password1 != password2){\r\n");
      out.write("		alert(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("		joinform.MEMBER_PW.value=\"\";\r\n");
      out.write("		joinform.MEMBER_PW2.value=\"\";\r\n");
      out.write("		joinform.MEMBER_PW.focus();\r\n");
      out.write("		return false;\r\n");
      out.write("	}\r\n");
      out.write("	if((forms.MEMBER_JUMIN1.value==\"\")||(forms.MEMBER_JUMIN1.value.length<6)){\r\n");
      out.write("		alert(\"주민등록번호 앞의 6자리를 입력해 주세요.\");\r\n");
      out.write("      	forms.MEMBER_JUMIN1.focus();\r\n");
      out.write("        return false;\r\n");
      out.write(" 	}\r\n");
      out.write(" 	if((forms.MEMBER_JUMIN2.value==\"\")||(forms.MEMBER_JUMIN2.value.length<7)){\r\n");
      out.write("		alert(\"주민등록번호 뒤의 7자리를 입력해 주세요.\");\r\n");
      out.write("      	forms.MEMBER_JUMIN2.focus();\r\n");
      out.write("        return false;\r\n");
      out.write("	} \r\n");
      out.write("	if(email1.length == 0 || email2.length ==0){\r\n");
      out.write("		alert(\"이메일을 제대로 입력하세요.\");\r\n");
      out.write("		joinform.MEMBER_EMAIL1.focus();\r\n");
      out.write("		return false;\r\n");
      out.write("	}\r\n");
      out.write("	if(phone.length == 0){\r\n");
      out.write("		alert(\"집 전화를 입력하세요.\");\r\n");
      out.write("		joinform.MEMBER_PHONE.focus();\r\n");
      out.write("		return false;\r\n");
      out.write("	} \r\n");
      out.write("	if((forms.MEMBER_ZIPCODE1.value==\"\")||(forms.MEMBER_ZIPCODE1.value.length<3)){\r\n");
      out.write("		alert(\"우편번호 앞의 3자리를 입력해 주세요.\");\r\n");
      out.write("      	forms.MEMBER_ZIPCODE1.focus();\r\n");
      out.write("        return false;\r\n");
      out.write(" 	}\r\n");
      out.write(" 	if((forms.MEMBER_ZIPCODE2.value==\"\")||(forms.MEMBER_ZIPCODE2.value.length<3)){\r\n");
      out.write("		alert(\"우편번호 뒤의 3자리 입력해 주세요.\");\r\n");
      out.write("      	forms.MEMBER_ZIPCODE2.focus();\r\n");
      out.write("        return false;\r\n");
      out.write("	}  \r\n");
      out.write("	if(addr1.length == 0){\r\n");
      out.write("		alert(\"집 주소를 입력하세요.\");\r\n");
      out.write("		joinform.MEMBER_ADDR1.focus();\r\n");
      out.write("		return false;\r\n");
      out.write("	} \r\n");
      out.write("	if(addr2.length == 0){\r\n");
      out.write("		alert(\"상세 주소를 입력하세요.\");\r\n");
      out.write("		joinform.MEMBER_ADDR2.focus();\r\n");
      out.write("		return false;\r\n");
      out.write("	} \r\n");
      out.write("	if(mobile.length == 0){\r\n");
      out.write("		alert(\"휴대폰 번호를 입력하세요.\");\r\n");
      out.write("		joinform.MEMBER_MOBILE.focus();\r\n");
      out.write("		return false;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	return true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function openConfirmId(joinform){			\r\n");
      out.write("	var id=joinform.MEMBER_ID.value;\r\n");
      out.write("	var url=\"./MemberIDCheckAction.me?MEMBER_ID=\"+joinform.MEMBER_ID.value;\r\n");
      out.write("	\r\n");
      out.write("	if(id.length == 0){\r\n");
      out.write("		alert(\"아이디를 입력하세요.\");\r\n");
      out.write("		joinform.MEMBER_ID.focus();\r\n");
      out.write("		return false;\r\n");
      out.write("	}\r\n");
      out.write("	open(url, \"confirm\", \"toolbar=no,location=no,status=no,menubar=no,\"+\r\n");
      out.write("						 \"scrollbars=no,resizable=no,width=400,height=200\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function openZipcode(joinform){			\r\n");
      out.write("	var url=\"./Zipcode.me\"\r\n");
      out.write("	open(url, \"confirm\", \"toolbar=no,location=no,\"\r\n");
      out.write("						+\"status=no,menubar=no,\"\r\n");
      out.write("						+\"scrollbars=yes,resizable=no,\"\r\n");
      out.write("						+\"width=410,height=400\");\r\n");
      out.write("}	\r\n");
      out.write("\r\n");
      out.write("function gNumCheck(){\r\n");
      out.write("	if(event.keyCode >=48 && event.keyCode <=57) {\r\n");
      out.write("		return true;\r\n");
      out.write("	}else{\r\n");
      out.write("		event.returnValue=false;	\r\n");
      out.write("	}\r\n");
      out.write("}		\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<table width=\"960\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" align=\"center\">\r\n");
      out.write("	<tr>\r\n");
      out.write("	<td colspan=2>\r\n");
      out.write("	<!-- 회원가입 -->\r\n");
      out.write("	<form name=\"joinform\" id=\"joinform\" action=\"./MemberJoinAction.me\" method=\"post\" \r\n");
      out.write("		onsubmit=\"return check()\">		\r\n");
      out.write("	<p align=\"center\">	\r\n");
      out.write("	<table border=\"1\" width=\"80%\" height=\"80%\">\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"17%\" bgcolor=\"#f5f5f5\">\r\n");
      out.write("			<font size=\"2\">&nbsp;&nbsp;&nbsp;&nbsp;이름</font>\r\n");
      out.write("		</td>\r\n");
      out.write("		<td>\r\n");
      out.write("			&nbsp;&nbsp;&nbsp;\r\n");
      out.write("			<input type=\"text\" name=\"MEMBER_NAME\" size=\"20\"/>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td bgcolor=\"#f5f5f5\">\r\n");
      out.write("			<font size=\"2\">&nbsp;&nbsp;&nbsp;&nbsp;아이디</font>\r\n");
      out.write("		</td>\r\n");
      out.write("		<td>\r\n");
      out.write("			&nbsp;&nbsp;&nbsp;\r\n");
      out.write("			<input type=\"text\" name=\"MEMBER_ID\" size=\"10\" maxlength=15/>\r\n");
      out.write("			<input type=\"button\" name=\"confirm_id\" value=\"중복확인\" \r\n");
      out.write("				onclick=\"openConfirmId(this.form)\" />\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td bgcolor=\"#f5f5f5\">\r\n");
      out.write("			<font size=\"2\">&nbsp;&nbsp;&nbsp;&nbsp;비밀번호</font>\r\n");
      out.write("		</td>\r\n");
      out.write("		<td>\r\n");
      out.write("			&nbsp;&nbsp;&nbsp;\r\n");
      out.write("			<input type=\"password\" name=\"MEMBER_PW\" size=\"15\"/>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td bgcolor=\"#f5f5f5\">\r\n");
      out.write("			<font size=\"2\">&nbsp;&nbsp;&nbsp;&nbsp;비밀번호 확인</font>\r\n");
      out.write("		</td>\r\n");
      out.write("		<td>\r\n");
      out.write("			&nbsp;&nbsp;&nbsp;\r\n");
      out.write("			<input type=\"password\" name=\"MEMBER_PW2\" size=\"15\" />\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td bgcolor=\"#f5f5f5\">&nbsp;</td>\r\n");
      out.write("		<td>\r\n");
      out.write("		<font size=\"2\">&nbsp;&nbsp;&nbsp;\r\n");
      out.write("		(아이디와 비밀번호는 문자와 숫자를 조합하여 2~12자리로 만들어 주세요)</font>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td bgcolor=\"#f5f5f5\">\r\n");
      out.write("			<font size=\"2\">&nbsp;&nbsp;&nbsp;&nbsp;주민등록번호</font>\r\n");
      out.write("		</td>\r\n");
      out.write("		<td>\r\n");
      out.write("			&nbsp;&nbsp;&nbsp;\r\n");
      out.write("			<input type=\"text\" name=\"MEMBER_JUMIN1\" size=\"12\" \r\n");
      out.write("				onkeypress=\"gNumCheck()\" maxlength=\"6\"/>-	\r\n");
      out.write("			<input type=\"text\" name=\"MEMBER_JUMIN2\" size=\"12\" \r\n");
      out.write("				onkeypress=\"gNumCheck()\" maxlength=\"7\"/>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td bgcolor=\"#f5f5f5\">\r\n");
      out.write("			<font size=\"2\">&nbsp;&nbsp;&nbsp;&nbsp;이메일 주소</font>\r\n");
      out.write("		</td>\r\n");
      out.write("		<td>\r\n");
      out.write("			&nbsp;&nbsp;&nbsp;\r\n");
      out.write("			<input type=\"text\" name=\"MEMBER_EMAIL1\" size=\"13\"/>@\r\n");
      out.write("			<input type=\"text\" name=\"MEMBER_EMAIL2\" size=\"15\"/> \r\n");
      out.write("		</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("		<td bgcolor=\"#f5f5f5\">\r\n");
      out.write("		<font size=\"2\">&nbsp;&nbsp;&nbsp;&nbsp;메일 수신 여부</font>\r\n");
      out.write("		</td>\r\n");
      out.write("		<td>\r\n");
      out.write("		&nbsp;&nbsp;&nbsp;\r\n");
      out.write("		<input type=\"radio\" name=\"MEMBER_EMAIL_GET\" value=\"YES\" checked/>\r\n");
      out.write("		<font size=\"2\">수신</font>\r\n");
      out.write("		&nbsp;&nbsp;<input type=\"radio\" name=\"MEMBER_EMAIL_GET\" value=\"NO\"/>\r\n");
      out.write("		<font size=\"2\">수신 안함</font>\r\n");
      out.write("		</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td bgcolor=\"#f5f5f5\">\r\n");
      out.write("				<font size=\"2\">&nbsp;&nbsp;&nbsp;&nbsp;집전화</font>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td>\r\n");
      out.write("				&nbsp;&nbsp;&nbsp;\r\n");
      out.write("				<input type=\"text\" name=\"MEMBER_PHONE\" size=\"24\"/>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td bgcolor=\"#f5f5f5\">\r\n");
      out.write("				<font size=\"2\">&nbsp;&nbsp;&nbsp;&nbsp;우편번호</font>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td>\r\n");
      out.write("			&nbsp;&nbsp;&nbsp;\r\n");
      out.write("			<input type=\"text\" name=\"MEMBER_ZIPCODE1\" size=\"6\" \r\n");
      out.write("				onkeypress=\"gNumCheck()\" maxlength=\"3\"/>- \r\n");
      out.write("			<input type=\"text\" name=\"MEMBER_ZIPCODE2\" size=\"6\" \r\n");
      out.write("				onkeypress=\"gNumCheck()\" maxlength=\"3\" />&nbsp;&nbsp;\r\n");
      out.write("			<input type=\"button\" name=\"zipcode\" value=\"우편번호 검색\" \r\n");
      out.write("				onclick=\"openZipcode(this.form)\" />\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td bgcolor=\"#f5f5f5\">\r\n");
      out.write("				<font size=\"2\">&nbsp;&nbsp;&nbsp;&nbsp;집주소</font>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td>\r\n");
      out.write("				&nbsp;&nbsp;&nbsp;\r\n");
      out.write("				<input type=\"text\" name=\"MEMBER_ADDR1\" size=\"50\" />\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td bgcolor=\"#f5f5f5\">\r\n");
      out.write("				<font size=\"2\">&nbsp;&nbsp;&nbsp;&nbsp;상세주소</font>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td>\r\n");
      out.write("				&nbsp;&nbsp;&nbsp;\r\n");
      out.write("				<input type=\"text\" name=\"MEMBER_ADDR2\" size=\"50\" />\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td bgcolor=\"#f5f5f5\">\r\n");
      out.write("				<font size=\"2\">&nbsp;&nbsp;&nbsp;&nbsp;휴대폰</font>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td>\r\n");
      out.write("				&nbsp;&nbsp;&nbsp;\r\n");
      out.write("				<input type=\"text\" name=\"MEMBER_MOBILE\" size=\"24\" />\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<table width=\"80%\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=\"center\">\r\n");
      out.write("					<br/><input type=\"submit\" value=\"확 인\" />\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		</form>\r\n");
      out.write("		<!-- 회원가입 -->	\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
