DROP TABLE MEMBER PURGE;
CREATE TABLE MEMBER( -- 회원관리용 테이블 (회원가입에서 전달받는 사용자의 정보를 저장)
	MEMBER_ID VARCHAR2(20),
	MEMBER_PW VARCHAR2(15),
	MEMBER_NAME VARCHAR2(20),
	MEMBER_JUMIN1 NUMBER,
	MEMBER_JUMIN2 NUMBER,
	MEMBER_EMAIL VARCHAR2(25),
	MEMBER_EMAIL_GET VARCHAR2(7), --광고를 수신하기 위한 이메일 컬럼
	MEMBER_MOBILE VARCHAR2(13),
	MEMBER_PHONE VARCHAR2(13),
	MEMBER_ZIPCODE VARCHAR2(13), --우편 번호 컬럼
	MEMBER_ADDR1 VARCHAR2(70), --일반 주소 컬럼
	MEMBER_ADDR2 VARCHAR2(70), --상세 주소 컬럼
	MEMBER_ADMIN NUMBER, --접속한 사람이 관리자인지를 체크하기 위한 컬럼
	MEMBER_JOIN_DATE DATE
);

DROP TABLE ZIPCODE PURGE;
CREATE TABLE ZIPCODE ( -- 우편번호에 대한 정보를 관리할 테이블 / 우체국의 웹사이트에서 제공해주는 주소(구) 버전을 통해 검색할 수 있도록 함 
  ID NUMBER,
  ZIPCODE VARCHAR2(7),
  SIDO VARCHAR2(10),
  GUGUN VARCHAR2(30),
  DONG VARCHAR2(36),
  RI VARCHAR2(60),
  BUNJI VARCHAR2(50),
  PRIMARY KEY (ID)
);

select * from MEMBER;
select * from ZIPCODE;

DROP TABLE GOODS PURGE;
CREATE TABLE GOODS( -- 상품에 대한 상세 정보를 관리할 테이블
	GOODS_NUM NUMBER, --상품 목록의 고유 번호
	GOODS_CATEGORY VARCHAR2(20), --카테고리별 관리(바지, 상의, 치마)
	GOODS_NAME VARCHAR2(50),
	GOODS_CONTENT VARCHAR2(3000), --상품의 상세 설명
	GOODS_SIZE VARCHAR2(10),
	GOODS_COLOR VARCHAR2(20),
	GOODS_AMOUNT NUMBER, --재고
	GOODS_PRICE NUMBER,
	GOODS_IMAGE VARCHAR2(50), --상품의 시각적인 이미지
	GOODS_BEST NUMBER, --잘팔리는 상품은 좀 더 상단에 뜨게하는 우선순위를 지정할 수 있도록 함.
	GOODS_DATE DATE,
	PRIMARY KEY(GOODS_NUM)
);

select * from GOODS;

DROP TABLE BASKET PURGE;
CREATE TABLE BASKET( -- 장바구니 테이블
	BASKET_NUM NUMBER,
	BASKET_MEMBER_ID VARCHAR2(20),
	BASKET_GOODS_NUM NUMBER,
	BASKET_GOODS_AMOUNT NUMBER,
	BASKET_GOODS_SIZE VARCHAR2(20),
	BASKET_GOODS_COLOR VARCHAR2(20),
	BASKET_DATE DATE,
	PRIMARY KEY(BASKET_NUM)
);

DROP TABLE GOODS_ORDER PURGE;
CREATE TABLE GOODS_ORDER( -- 사용자의 주문과 관련된 정보를 관리할 테이블
	ORDER_NUM NUMBER,
	ORDER_TRADE_NUM VARCHAR2(50),
	ORDER_TRANS_NUM VARCHAR2(50),
	ORDER_GOODS_NUM	NUMBER,
	ORDER_GOODS_NAME VARCHAR2(50),
	ORDER_GOODS_AMOUNT NUMBER,
	ORDER_GOODS_SIZE VARCHAR2(20),
	ORDER_GOODS_COLOR VARCHAR2(20),
	ORDER_MEMBER_ID VARCHAR2(20),
	ORDER_RECEIVE_NAME VARCHAR2(20),
	ORDER_RECEIVE_ADDR1 VARCHAR2(70),
	ORDER_RECEIVE_ADDR2 VARCHAR2(70),
	ORDER_RECEIVE_PHONE VARCHAR2(13),
	ORDER_RECEIVE_MOBILE VARCHAR2(13),
	ORDER_MEMO VARCHAR2(3000),
	ORDER_SUM_MONEY NUMBER,
	ORDER_TRADE_TYPE VARCHAR2(20),
	ORDER_TRADE_DATE DATE,
	ORDER_TRADE_PAYER VARCHAR2(20),
	ORDER_DATE DATE,
	ORDER_STATUS NUMBER,
	PRIMARY KEY(ORDER_NUM)
);

DELETE FROM BASKET;

SELECT * FROM basket;