/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-09 08:14:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.goods;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import net.goods.db.*;

public final class goods_005fdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:trim", org.apache.taglibs.standard.functions.Functions.class, "trim", new Class[] {java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1680508892000L));
    _jspx_dependants.put("jar:file:/C:/workspaces/jsp/src/ShoppingMall/src/main/webapp/WEB-INF/lib/standard.jar!/META-INF/fn.tld", Long.valueOf(1064301420000L));
    _jspx_dependants.put("jar:file:/C:/workspaces/jsp/src/ShoppingMall/src/main/webapp/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1064301420000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("net.goods.db");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforTokens_0026_005fvar_005fitems_005fdelims;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforTokens_0026_005fvar_005fitems_005fdelims = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforTokens_0026_005fvar_005fitems_005fdelims.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	GoodsBean itemArray = (GoodsBean) request.getAttribute("itemArray");
	String category = (String) request.getAttribute("item");
	String price = (String) request.getAttribute("price");

	GoodsBean prevpage = (GoodsBean) request.getAttribute("prevpage");
	GoodsBean nextpage = (GoodsBean) request.getAttribute("nextpage");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>쇼핑몰</title>\r\n");
      out.write("<script>\r\n");
      out.write("function isBuy(goodsform) {\r\n");
      out.write("	if (document.goodsform.size.value==\"\") {\r\n");
      out.write("		alert(\"사이즈를 선택해주세요.\")\r\n");
      out.write("		return;\r\n");
      out.write("	} else if (document.goodsform.color.value==\"\") {\r\n");
      out.write("		alert(\"색상을 선택해주세요.\")\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	var amount=document.goodsform.amount.value;\r\n");
      out.write("	var size=document.goodsform.size.value;;\r\n");
      out.write("	var type=document.goodsform.color.value;;\r\n");
      out.write("	\r\n");
      out.write("	var isbuy=confirm(\"구매하시겠습니까?\");\r\n");
      out.write("	if(isbuy==true) {\r\n");
      out.write("		goodsform.action=\"OrderStart.or\";\r\n");
      out.write("		goodsform.submit();\r\n");
      out.write("	} else {\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function isBasket(basketform) {\r\n");
      out.write("	if (document.goodsform.size.value==\"\") {\r\n");
      out.write("		alert(\"사이즈를 선택해주세요.\")\r\n");
      out.write("		return;\r\n");
      out.write("	} else if (document.goodsform.color.value==\"\") {\r\n");
      out.write("		alert(\"색상을 선택해주세요.\")\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	var amount=document.goodsform.amount.value;\r\n");
      out.write("	var size=document.goodsform.size.value;;\r\n");
      out.write("	var type=document.goodsform.color.value;;\r\n");
      out.write("	\r\n");
      out.write("	var isbuy=confirm(\"장바구니에 저장하시겠습니까?\");\r\n");
      out.write("	\r\n");
      out.write("	if(isbuy==true) {\r\n");
      out.write("		basketform.action=\"BasketAdd.ba\";\r\n");
      out.write("		basketform.submit();\r\n");
      out.write("	} else {\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function count_change(temp){\r\n");
      out.write("	var test=document.goodsform.amount.value;\r\n");
      out.write("	if(temp==0){\r\n");
      out.write("		test++;\r\n");
      out.write("	}else if(temp==1){\r\n");
      out.write("		if(test> 1) test--;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	document.goodsform.amount.value=test;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<table width=\"960\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" align=\"center\">\r\n");
      out.write("	<tr>\r\n");
      out.write("	  <td colspan=2 align=center><!-- 상품 내용 -->\r\n");
      out.write("		<form name=\"goodsform\" action=\"#\" method=\"post\">\r\n");
      out.write("			<input type=\"hidden\" name=\"goodsnum\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${itemArray.GOODS_NUM }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("			<input type=\"hidden\" name=\"item\" value=\"");
      out.print(request.getParameter("item") );
      out.write("\"> \r\n");
      out.write("			<input type=\"hidden\" name=\"gr_goods_num\" value=\"");
      out.print(request.getParameter("gr_goods_num") );
      out.write("\">\r\n");
      out.write("			<input type=\"hidden\" name=\"isitem\" value=\"");
      out.print(request.getParameter("isitem") );
      out.write("\">\r\n");
      out.write("			<input type=\"hidden\" name=\"order\" value=\"goods\">\r\n");
      out.write("			<input type=\"hidden\" name=\"price\" value=\"");
      out.print(itemArray.getGOODS_PRICE() );
      out.write("\">\r\n");
      out.write("			<input type=\"hidden\" name=\"goodsname\" value=\"");
      out.print(itemArray.getGOODS_NAME() );
      out.write("\"> \r\n");
      out.write("			<input type=\"hidden\" name=\"goodsimage\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:trim(mainImage)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\">\r\n");
      out.write("		\r\n");
      out.write("			<table width=\"600\" border=\"0\" align=\"center\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td height=\"60\" colspan=\"2\">상 세 보 기</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td width=\"303\" height=\"223\" align=\"center\" valign=\"middle\">\r\n");
      out.write("						<img src=\"./upload/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:trim(mainImage)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\" width=\"300\" height=\"300\"/>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td width=\"381\" align=\"center\" valign=\"middle\">\r\n");
      out.write("						<table width=\"300\" height=\"200\" border=\"0\">\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td colspan=\"4\" align=\"center\" height=\"50\">\r\n");
      out.write("									<b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${itemArray.GOODS_NAME}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b>\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td>판매가격 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:</td>\r\n");
      out.write("								<td colspan=\"3\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${itemArray.GOODS_PRICE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 원</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td rowspan=\"2\">수량\r\n");
      out.write("									&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("									&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:\r\n");
      out.write("								</td>\r\n");
      out.write("								<td width=\"58\" rowspan=\"2\">\r\n");
      out.write("									<input name=\"amount\" type=\"text\" style=\"text-align: right\" value=\"1\" size=\"4\"/>\r\n");
      out.write("								</td>\r\n");
      out.write("								<td valign=\"bottom\">\r\n");
      out.write("									<div align=\"center\">\r\n");
      out.write("										<a href=\"JavaScript:count_change(0)\">▲</a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</td>\r\n");
      out.write("								<td width=\"69\" rowspan=\"2\" align=\"left\">개</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td valign=\"top\">\r\n");
      out.write("									<div align=\"center\">\r\n");
      out.write("										<a href=\"JavaScript:count_change(1)\">▼</a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td align=\"left\" colspan=\"4\" height=\"30\" align=\"middle\">\r\n");
      out.write("									남은수량(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${itemArray.GOODS_AMOUNT }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")개\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td colspan=\"4\">크기&nbsp;&nbsp;&nbsp;&nbsp; \r\n");
      out.write("									<select name=\"size\" size=\"1\">\r\n");
      out.write("										<option value=\"\">크기를 선택하세요</option>\r\n");
      out.write("										<option value=\"\">-----------------</option>\r\n");
      out.write("			\r\n");
      out.write("										");
      if (_jspx_meth_c_005fforTokens_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("									</select>\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td colspan=\"4\">색깔&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("									<select name=\"color\" size=\"1\">\r\n");
      out.write("										<option value=\"\">색깔을 선택하세요</option>\r\n");
      out.write("										<option value=\"\">-----------------</option>\r\n");
      out.write("										");
      if (_jspx_meth_c_005fforTokens_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("									</select>\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td height=\"50\" colspan=\"4\">&nbsp;</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td colspan=\"4\">\r\n");
      out.write("									<a href=\"javascript:isBuy(goodsform);\">\r\n");
      out.write("										[구매하기]\r\n");
      out.write("									</a> \r\n");
      out.write("									<a href=\"javascript:isBasket(goodsform);\">\r\n");
      out.write("										[장바구니 담기]\r\n");
      out.write("									</a>\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"center\"></td>\r\n");
      out.write("					<td>&nbsp;</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("				<td colspan=\"2\">\r\n");
      out.write("				<table align=\"center\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>\r\n");
      out.write("						");

						if (prevpage.getGOODS_NUM() != 0) {
							if (price.equals("no")) {
						
      out.write("\r\n");
      out.write("							<a href=\"Goods_Detail.go?search=prev\r\n");
      out.write("							&gr_goods_num=");
      out.print(itemArray.getGOODS_NUM());
      out.write("\r\n");
      out.write("							&item=");
      out.print(category);
      out.write("\">\r\n");
      out.write("						");

							} else {
						
      out.write(" \r\n");
      out.write("							<a href=\"Goods_Detail.go?search=prev\r\n");
      out.write("							&gr_goods_num=");
      out.print(itemArray.getGOODS_NUM());
      out.write("\r\n");
      out.write("							&item=");
      out.print(category);
      out.write("&price=");
      out.print(price);
      out.write("\">\r\n");
      out.write("						");

							}
						
      out.write("\r\n");
      out.write("							[이전상품] \r\n");
      out.write("							</a>\r\n");
      out.write("						</td>\r\n");
      out.write("						<td width=\"100\" align=\"left\">\r\n");
      out.write("						<div align=\"center\">\r\n");
      out.write("							<img src=\"./upload/");
      out.print(prevpage.getGOODS_IMAGE());
      out.write("\" width=\"70\" height=\"50\" border=\"0\">\r\n");
      out.write("							<br>");
      out.print(prevpage.getGOODS_NAME());
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("						</td>\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("						<td width=\"100\" align=\"right\">\r\n");
      out.write("						");

						if (nextpage.getGOODS_NUM() != 0) {
						
      out.write("\r\n");
      out.write("							<div align=\"center\">\r\n");
      out.write("							<img src=\"./upload/");
      out.print(nextpage.getGOODS_IMAGE());
      out.write("\" width=\"70\" height=\"50\" border=\"0\">\r\n");
      out.write("							<br>");
      out.print(nextpage.getGOODS_NAME());
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("						</td>\r\n");
      out.write("						<td>\r\n");
      out.write("						");

							if (price.equals("no")) {
						
      out.write("\r\n");
      out.write("							<a href=\"Goods_Detail.go?search=next\r\n");
      out.write("							&gr_goods_num=");
      out.print(itemArray.getGOODS_NUM());
      out.write("\r\n");
      out.write("							&item=");
      out.print(category);
      out.write("\"/>\r\n");
      out.write("						");

							} else {
						
      out.write("\r\n");
      out.write("							<a href=\"Goods_Detail.go?search=next\r\n");
      out.write("							&gr_goods_num=");
      out.print(itemArray.getGOODS_NUM());
      out.write("\r\n");
      out.write("							&item=");
      out.print(category);
      out.write("&price=");
      out.print(price);
      out.write("\"/>\r\n");
      out.write("						");

							}
						
      out.write(" [다음상품] \r\n");
      out.write("							</a>\r\n");
      out.write("						");

	 					}
	 					
      out.write("\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</form><!-- 상품 구매 메뉴 끝 -->\r\n");
      out.write("		\r\n");
      out.write("		<!-- 상품 내용 -->\r\n");
      out.write("		<table width=\"700\" height=\"300\" align=\"enter\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=\"center\">\r\n");
      out.write("				<div>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${itemArray.GOODS_CONTENT }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<br><br>\r\n");
      out.write("		<table width=\"200\" border=\"0\" align=\"center\">\r\n");
      out.write("			<tr align=\"left\">\r\n");
      out.write("				<td colspan=\"3\">\r\n");
      out.write("					");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<!-- 상품 내용 끝 --></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforTokens_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forTokens
    org.apache.taglibs.standard.tag.rt.core.ForTokensTag _jspx_th_c_005fforTokens_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForTokensTag) _005fjspx_005ftagPool_005fc_005fforTokens_0026_005fvar_005fitems_005fdelims.get(org.apache.taglibs.standard.tag.rt.core.ForTokensTag.class);
    boolean _jspx_th_c_005fforTokens_005f0_reused = false;
    try {
      _jspx_th_c_005fforTokens_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforTokens_005f0.setParent(null);
      // /goods/goods_detail.jsp(143,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f0.setVar("size");
      // /goods/goods_detail.jsp(143,10) name = items type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${itemArray.GOODS_SIZE}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /goods/goods_detail.jsp(143,10) name = delims type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f0.setDelims(",");
      int[] _jspx_push_body_count_c_005fforTokens_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforTokens_005f0 = _jspx_th_c_005fforTokens_005f0.doStartTag();
        if (_jspx_eval_c_005fforTokens_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("											<option value=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:trim(size)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
            out.write(">\r\n");
            out.write("												");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:trim(size)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
            out.write("\r\n");
            out.write("											</option>\r\n");
            out.write("										");
            int evalDoAfterBody = _jspx_th_c_005fforTokens_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforTokens_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforTokens_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforTokens_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforTokens_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforTokens_0026_005fvar_005fitems_005fdelims.reuse(_jspx_th_c_005fforTokens_005f0);
      _jspx_th_c_005fforTokens_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforTokens_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforTokens_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforTokens_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forTokens
    org.apache.taglibs.standard.tag.rt.core.ForTokensTag _jspx_th_c_005fforTokens_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForTokensTag) _005fjspx_005ftagPool_005fc_005fforTokens_0026_005fvar_005fitems_005fdelims.get(org.apache.taglibs.standard.tag.rt.core.ForTokensTag.class);
    boolean _jspx_th_c_005fforTokens_005f1_reused = false;
    try {
      _jspx_th_c_005fforTokens_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforTokens_005f1.setParent(null);
      // /goods/goods_detail.jsp(156,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f1.setVar("color");
      // /goods/goods_detail.jsp(156,10) name = items type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${itemArray.GOODS_COLOR}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /goods/goods_detail.jsp(156,10) name = delims type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f1.setDelims(",");
      int[] _jspx_push_body_count_c_005fforTokens_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforTokens_005f1 = _jspx_th_c_005fforTokens_005f1.doStartTag();
        if (_jspx_eval_c_005fforTokens_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("											<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:trim(color)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
            out.write("\">\r\n");
            out.write("												");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:trim(color)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
            out.write("\r\n");
            out.write("											</option>\r\n");
            out.write("										");
            int evalDoAfterBody = _jspx_th_c_005fforTokens_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforTokens_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforTokens_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforTokens_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforTokens_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforTokens_0026_005fvar_005fitems_005fdelims.reuse(_jspx_th_c_005fforTokens_005f1);
      _jspx_th_c_005fforTokens_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforTokens_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforTokens_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /goods/goods_detail.jsp(266,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("itemimg");
      // /goods/goods_detail.jsp(266,5) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.contentImage}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("						<img src=\"./upload/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:trim(itemimg)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
            out.write("\" />\r\n");
            out.write("					");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
